# file setting
camera_file: ./camera_calibration.yaml
weights: pretrained_model_KITTI2015.tar

# publisher
depth_publisher: camera/depth_image
color_publisher: camera/color_image

# subscriber
left_image_sub: /stereo/slave/left/image
right_image_sub: /stereo/slave/right/image
mask_image_sub: /stereo/viewer/left/image

# parameters for applying mask
mask_offset: 100
dilation_size: 9

# original image size
input_img_width: 1920
input_img_height: 1080

# scale the input image after receiving
scaleing_factor: 2

# output depth map size
output_img_width: 640
output_img_height: 480

# depth scaling for fusion
depth_scaling : 10

# sleep time between each msg
sleep_time: 0.0
